### ISSUE TITLE
Provide option for `.get_next()` and `.get_prev()` to include current

### ISSUE THREAD

**Issue by sushinoya** [pallets-eco/croniter#10]
Currently, `get_next` and `get_prev` do not account for whether the current time is a match for the cron. They strictly mean next and previous exclusive of the current time - 

```python
>>> from croniter import croniter
>>> from datetime import datetime
>>> croniter(" 0 5 * * *", datetime(2020, 1, 1, 5, 0, 0)).get_next(datetime)
datetime.datetime(2020, 1, 2, 5, 0)
>>> croniter(" 0 5 * * *", datetime(2020, 1, 1, 5, 0, 0)).get_prev(datetime)
datetime.datetime(2019, 12, 31, 5, 0)
```

This is reasonable behaviour but I think it would be better if we can give the users a choice to include the current time as well. So perhaps an extra argument like - 

```python
>>> from croniter import croniter
>>> from datetime import datetime
>>> croniter(" 0 5 * * *", datetime(2020, 1, 1, 5, 0, 0)).get_next(datetime, incl_current=True)
datetime.datetime(2020, 1, 1, 5, 0)
>>> croniter(" 0 5 * * *", datetime(2020, 1, 1, 5, 0, 0)).get_prev(datetime, incl_current=True)
datetime.datetime(2020, 1, 1, 5, 0)
```

I've noticed users subtracting one second from the current time to make it inclusive or using `croniter.match` with current time first then calling on `get_next` or `get_prev` which works but is a bit more verbose. Neither of these options seem very ideal.

**Comment by kiorky** [comment]
Thanks for the idea, but I'm against this philosophy as this won't go along with [UNIX implementation](https://en.wikipedia.org/wiki/Cron) from which croniter sticks the most.

For this, you'd better to provide in your API a wrapper or subclass to croniter to make the current datetime inclusion.

**Comment by sushinoya** [comment]
Hi! Sure, I guess that's up to you. Also, the wikipedia page was not very useful. Could you could pinpoint me to what aspect of the current cron implementation this contradicts? After all croniter is a cron "iterator" and the UNIX cron/crontab isn't and so I would expect subtle differences like this.

**Comment by kiorky** [comment]
No, croniter spirit was always to be used in the UNIX philosophy.
So current time has not to be present in the next/prev series.
