### ISSUE TITLE
Croniter mark as valid `10 0 1-5 * 2#2`

### ISSUE THREAD

**Issue by spk** [pallets-eco/croniter#16]
The last part `#2` is meant to be a comment, this is valid for `is_valid`

```
>>> croniter.is_valid('10 0 1-5 * 2#2')
True
```

but later fail is we try to do a next time with:

```
>>> from croniter import croniter
>>> from datetime import datetime
>>> base = datetime(2010, 1, 25, 4, 46)
>>> iter = croniter('10 0 1-5 * 2#2', base)
>>> print(iter.get_next(datetime))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/spk/dev/foundation/testbed/.env/local/lib/python2.7/site-packages/croniter/croniter.py", line 179, in get_next
    return self._get_next(ret_type or self._ret_type, is_prev=False)
  File "/home/spk/dev/foundation/testbed/.env/local/lib/python2.7/site-packages/croniter/croniter.py", line 246, in _get_next
    t1 = self._calc(self.cur, expanded, nth_weekday_of_month, is_prev)
  File "/home/spk/dev/foundation/testbed/.env/local/lib/python2.7/site-packages/croniter/croniter.py", line 527, in _calc
    raise CroniterBadDateError("failed to find next date")
croniter.croniter.CroniterBadDateError: failed to find next date
```

Most of the online tools mark this as an error.

* https://crontab.guru/#10_0_1-5_*_2#2
* https://freeformatter.com/cron-expression-generator-quartz.html

![Screenshot from 2022-05-18 14-27-32](https://user-images.githubusercontent.com/98590/169038538-fab65d92-692a-495b-859c-c364b2340f33.png)

Maybe we should mark it invalid directly on `is_valid`?

**Comment by garithd** [comment]
Similar issue with this notation:
```
*/30 * * * * *
```

Shown to be invalid with these tools:
https://crontab.guru/#*/30_*_*_*_*_*
https://freeformatter.com/cron-expression-generator-quartz.html

**Comment by garithd** [comment]
Following on from my previous comment.
I'm using croniter to validate crons before creating a local linux crontab which is less forgiving on the format, specifically spaces and the number of items (5 versus 6). Would it be possible to have a key argument on ```is_valid``` to specify the amount of items (5 versus 6) in the cron? And also be strict on extra spaces before, during and trailing a cron string?

Would be great to even specify the format, i.e ```is_valid(format='unix')``` or ```is_valid(format='aws_event_bridge')```

**Comment by wasilaq** [comment]
This is also an issue when the cron expression points to February 30th or 31st. `croniter.is_valid('0 0 30 2 *')` returns `True` but trying to get the next date gives you an error since 2/30 and 2/31 don't actually exist.

**Comment by kiorky** [comment]
Croniter only officialy supports UNIX format (5 fields).

6th fields and other variants are community based.

PR are welcome :o).
