### ISSUE TITLE
Not Compatible with AWS Cron

### ISSUE THREAD

**Issue by AchimGrolimund** [pallets-eco/croniter#18]
`sched = '1 3 ? 3,10 SUN *'`

this is a valid AWS eventbridge cron
![image](https://user-images.githubusercontent.com/22026079/172594182-e14ced21-60d7-471c-a3d9-ad6d7709e240.png)

but Croniter raise this message:
`"errorMessage": "[1 3 ? 3,10 sun *] is not acceptable",`

gives any solution to use croniter with aws eventBridge rules?

here the full code:
```python
    now = datetime.datetime.now()
    sched = '1 3 ? 3,10 SUN *'
    cron = croniter.croniter(sched, now)
    for i in range(4):
        nextdate = cron.get_next(datetime.datetime)
        logger.info(nextdate)
```

Best regards

**Comment by kiorky** [comment]
Sorry but i'm afraid croniter mostly stick with UNIX like cron.

You may submit a PR to add the support, through.
