### ISSUE TITLE
seconds field is conventionally at the front

### ISSUE THREAD

**Issue by sanderr** [pallets-eco/croniter#19]
As far as I gather the seconds field in a cron expression (if it exists at all) is conventionally the first field. This is even described by the Wikipedia article mentioned in the docs. However, for croniter it seems to be the last field instead. Most importantly I think this should be stated explicitly in the docs. Additionally, it would be nice to see it moved to the front, though this would be a breaking change (major version bump?) and it might not be straightforward given how the parsing is currently implemented.

**Comment by kiorky** [comment]
nope, seconds is not part of unix cron.

**Comment by kiorky** [comment]
(see https://github.com/kiorky/croniter/issues/4#issuecomment-979110224)
