### ISSUE TITLE
Cannot use croniter with cron having 7 subexpression

### ISSUE THREAD

**Issue by sonivi** [pallets-eco/croniter#22]
Unable to use croniter with cron expression have 7 subexpression for e.g. '0 0 0/1 1/1 * ? *'

can we please support cron expression having 7 subexpression

**Comment by sonivi** [comment]
Due to this condition https://github.com/kiorky/croniter/blob/master/src/croniter/croniter.py#L619, getting CroniterBadCronError

**Comment by kiorky** [comment]
as said on #18 


Sorry but i'm afraid croniter mostly stick with UNIX like cron.

You may submit a PR to add the support, through.

**Comment by kiorky** [comment]
(duplicate #18)
