### ISSUE TITLE
Add type annotations to the codebase

### ISSUE THREAD

**Issue by edgarrmondragon** [pallets-eco/croniter#23]
This library still supports Python 2.7, so I'm not sure if this currently possible.

Another, less ideal, option would be to add [stub files](https://mypy.readthedocs.io/en/stable/stubs.html).

**Comment by ryanwersal** [comment]
It's an external package but there is a [stub types package](https://pypi.org/project/types-croniter/) from [typeshed](https://github.com/python/typeshed).

**Comment by edgarrmondragon** [comment]
@ryanwersal oh that's probably why there wasn't any other issue for it in this repo. I'll use `types-croniter` then, thanks!
