### ISSUE TITLE
croniter.match unexpected output 

### ISSUE THREAD

**Issue by TaridaGeorge** [pallets-eco/croniter#29]
I'm trying to understand why does this croniter.match call returns True:
```
    iter = croniter("* * * * * 2,4", datetime(2023, 1, 1, 0, 0, 1))
    print(iter.get_next(datetime))
    print(iter.get_next(datetime))
    print(iter.get_next(datetime))
    print(iter.get_next(datetime))

    print(croniter.match("* * * * * 2,4", datetime(2023, 1, 1, 0, 0, 1)))
```
Output is:

```
    2023-01-01 00:00:02
    2023-01-01 00:00:04
    2023-01-01 00:01:02
    2023-01-01 00:01:04
    True
```

You can see that I'm matching it against a datetime that has 1 in the seconds place.
Is this the indented behavior or is it a bug?

**Comment by waltervos** [comment]
As far as I can tell, your cron expression says "every second", as you're using the six positions syntax.

**Comment by TaridaGeorge** [comment]
But then why does iter.get_next(datetime) returns 00:00:02 then 00:00:04 then again 00:01:02, 00:01:04?

**Comment by waltervos** [comment]
I'm sorry, I didn't look close enough. I've always thought that the seconds field was the first field (when using seconds).

**Comment by waltervos** [comment]
I had a closer look now. croniter only matches for minute precision cron expressions. Refer to line 806: https://github.com/kiorky/croniter/blob/master/src/croniter/croniter.py#L806

I'm not sure if this is something that has been overlooked or if it's intentional.

**Comment by TaridaGeorge** [comment]
Yes. That seems to be the problem. It only matches for minute precision.

**Comment by kiorky** [comment]
as said on #18 


Sorry but i'm afraid croniter mostly stick with UNIX like cron.

You may submit a PR to add the support, through.

**Comment by waltervos** [comment]
@kiorky Shouldn't croniter just choose more definitively whether it supports seconds or not? The functionality is kind of half-implemented now. Would you welcome a PR that fixes this?

**Comment by kiorky** [comment]
Its on the README: croniter iterates along with cron_format from start_time. cron_format is min hour day month day_of_week,

**Comment by kiorky** [comment]
(And yes, as always, i would greatly appreciate a PR where things may be clearer)

PR are always welcome !
