### ISSUE TITLE
Request to be added to Croniter OSS-Fuzzer project members

### ISSUE THREAD

**Issue by sg3-141-592** [pallets-eco/croniter#32]
Hi there @kiorky ,

I've been improving the coverage on the Google OSS-Fuzz integration for Croniter https://github.com/google/oss-fuzz/pull/9860 . See https://storage.googleapis.com/oss-fuzz-introspector/croniter/inspector-report/20230317/fuzz_report.html for current status.

There's some issues with the updates to the fuzzer. Currently the only people who can see the stack traces for the errors are people listed in this file https://github.com/google/oss-fuzz/blob/master/projects/croniter/project.yaml . Would you mind me adding my e-mail address to this file? I need a maintainers permissions to be added to it to debug what's wrong.

Thanks for the library, it's been great for building some scheduled start/stop VM cost optimisation work recently.

**Comment by kiorky** [comment]
you can.
