### ISSUE TITLE
expression not support 6 columns when contain 'L'

### ISSUE THREAD

**Issue by wxyvgo** [pallets-eco/croniter#4]
when expression as below:
iter = croniter('30 0/20 4 L 1/2 10', base)

here is traceback,  because ALPHACONV has key error.
Traceback (most recent call last):
  File "D:\temp\202111\t_croniter.py", line 15, in <module>
    iter = croniter('30 0/20 4 L 1/2 10', base)
  File "D:\odoo\runtime\python3\lib\site-packages\croniter\croniter.py", line 154, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "D:\odoo\runtime\python3\lib\site-packages\croniter\croniter.py", line 762, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "D:\odoo\runtime\python3\lib\site-packages\croniter\croniter.py", line 711, in _expand
    t = cls._alphaconv(i, t, expressions)
  File "D:\odoo\runtime\python3\lib\site-packages\croniter\croniter.py", line 166, in _alphaconv
    "[{0}] is not acceptable".format(" ".join(expressions)))
croniter.croniter.CroniterNotAlphaError: [30 0/20 4 l 1/2 10] is not acceptable

the code should judge the length of expression when 6 columns, and if true the index should -1.
here is my patch: 
    @classmethod
    def _alphaconv(cls, index, key, expressions):
        try:
            # wade wang patch
            if len(expressions) == 6:
                return cls.ALPHACONV[index-1][key]
            # end of patch
            return cls.ALPHACONV[index][key]
        except KeyError:
            raise CroniterNotAlphaError(
                "[{0}] is not acceptable".format(" ".join(expressions)))

**Comment by kiorky** [comment]
croniter mostly stick with basic unix cron  (5 columns) support and extra features are only community maintained.

I wont fix those bugs.

You can always (you will be welcome !) make a PR with additional support for those range topics with proper tests, and i wont see anything that would prevent me from merging them.
