### ISSUE TITLE
datetime.utcnow and datetime.utcfromtimestamp are deprecated in Python 3.12

### ISSUE THREAD

**Issue by tirkarthi** [pallets-eco/croniter#49]
> datetime.datetime’s utcnow() and utcfromtimestamp() are deprecated and will be removed in a future version. Instead, use timezone-aware objects to represent datetimes in UTC: respectively, call now() and fromtimestamp() with the tz parameter set to datetime.UTC. (Contributed by Paul Ganssle in python/cpython#103857.)

```
croniter/src/croniter/tests/test_croniter.py
960:            dt = datetime.utcfromtimestamp(c.get_next())
980:            dt = datetime.utcfromtimestamp(c.get_next())
1003:            dt = datetime.utcfromtimestamp(c.get_next())

croniter/src/croniter/croniter.py
230:        result = datetime.datetime.utcfromtimestamp(timestamp)
862:        start, stop = (datetime.datetime.utcfromtimestamp(t) for t in (start, stop))
```

**Comment by kiorky** [comment]
I do not see a fix for now, as i m not willing to drop support for python2...
