### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ml31415** [pallets-eco/croniter#57]
While considering to use `croniter` for my own projects I had a closer look at the source code. Things that came to my mind:

- `croniter` is currently a god-class anti-pattern. It contains many `@classmethod` calls and constants, that probably would make more sense as module constants and plain / private functions instead of being part of the class.
- It might make sense to split it into `class CronIter` and a constructor function `croniter`, preserving the same interface as currently presented while sticking with PEP8 naming. All the setup / string parsing code could go to the constructor function then.
- It's a bit weird to change the return type within an iteration, so the `ret_type` keyword should be part of the init.
- `get_next` has a `start_time` argument, `get_prev` doesn't. This should be symmetrical.
- The code might make use of modern python3 features like f-strings and deprecate python2.
- using pytest instead of unittest would make the testing code much cleaner.
- pyproject.toml should replace setup.cfg etc.

If there is any interest in these changes, I'd be happy to provide some patches.

**Comment by kiorky** [comment]
"Hello"...

- as said in numerous bug croniter will stay py2 compatible to at least 2027.
- croniter was written by a non python programmer (not me but @taichino), more than 15 years ago, you should be humble and thanks him before all and know that code may suffer from history.
- get_next/get_prev aren't the same.
- You are telling more of a rewrite that little changes but m changing and modernizing such a codebase at once will just totally break retro-compatibility, which is very important to keep with croniter.
- test glue is also here in place and will not be changed every time there is a new cool way of doing things. Croniter is maintained by volunteers, we can't afford to spend time on something which is totally fine for now even if we did things now, we would of course use current best practices.

So, please, feel free to fork and create a project with all the bells and whistles you need. but i'm not interested AT ALL by someone introducing so much criticism at first without knowing the project history and goals, and without having looking at similar bugs which were answered.
