### ISSUE TITLE
[Q] ERROR 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by sixTiger** [pallets-eco/croniter#65]
django_q

arrow==1.3.0
asgiref==3.7.2
blessed==1.20.0
certifi==2024.2.2
charset-normalizer==3.3.2
croniter==2.0.2
Django==4.2.11
django-picklefield==3.1
django-q==1.3.9
idna==3.6
python-dateutil==2.9.0.post0
pytz==2024.1
redis==3.5.3
requests==2.31.0
rollbar==1.0.0
six==1.16.0
sqlparse==0.4.4
types-python-dateutil==2.9.0.20240315
typing_extensions==4.10.0
urllib3==2.2.1
uWSGI==2.0.24
wcwidth==0.2.13

**Comment by kiorky** [comment]
Sorry but you bug report does not have enough information.

Please report to us an exact use case / reproducible code for your problem.

(will close in one month if no further information)
