### ISSUE TITLE
Behaviour of get_next method when day changes

### ISSUE THREAD

**Issue by daleschyov** [pallets-eco/croniter#74]
Is it a bug or a feature? 
When the day changes during calling get_next method, the resulting value is just the starting point of defined schedule.
<img width="316" alt="image" src="https://github.com/kiorky/croniter/assets/47397283/415ba1a6-4298-4c73-ae4b-c466c6a8b9ce">

Thank you in advance for an answer

**Comment by kiorky** [comment]
Seems its ok as it's how it works with unix cron: `*` in day field always starts each day resetting from midnight, and need to still respect the criteria (in most of your samples,  `>=19h`).

**Comment by daleschyov** [comment]
Oh, sorry, my bad - misunderstood cron syntax... 
Thanks to your answer I understood, how to get the schedule I want, thank you!
