### ISSUE TITLE
support question mark

### ISSUE THREAD

**Issue by yyscamper** [pallets-eco/croniter#77]
many  of crontab implemenation support question mark on DayOfWeek and DayOfMonth field:

- https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm
- https://en.wikipedia.org/wiki/Cron
- https://techdocs.broadcom.com/us/en/symantec-security-software/endpoint-security-and-management/cloud-workload-protection-for-storage/1-0/Scan_Configuration_7/about-special-characters-in-cron-expressions-v123769576-d4995e65374.html

if croniter supports question mark as well, it will be bettter to cover more cases.

**Comment by kiorky** [comment]
If you want such a feature, i'm not against, but you ll have to submit a PR for :-).

**Comment by kiorky** [comment]
released as 2.0.6

**Comment by yyscamper** [comment]
thanks for @JabberWocky-22
