### ISSUE TITLE
Receiving the next or previous iteration always affects the current iteration

### ISSUE THREAD

**Issue by Fliens** [pallets-eco/croniter#83]
I want to get the previous or next iteration without affecting the current iteration that can be received with get_current() function.
Is there a way to get this behaviour?
Otherwise a simple if statement above line 363 with some function parameters could introduce this functionality.

**Comment by kiorky** [comment]
Would reverse next/prev the same to undo the consumed iterations solve your problem ?

eg if you
```
>>> iter.get_next(datetime) 
>>> iter.get_next(datetime) 
>>> iter.get_next(datetime) 
```

Then, if you do

```
>>> iter.get_prev(datetime) 
>>> iter.get_prev(datetime) 
>>> iter.get_prev(datetime) 
```

you should be in same state, and such one function is easy to write.

**Comment by Fliens** [comment]
Thank you for the response but this seems like an extremely hacky solution.

**Comment by kiorky** [comment]
> Thank you for the response but this seems like an extremely hacky solution.

Why so, croniter is an iterator, every iteration is reproducible.

**Comment by Fliens** [comment]
I do understand that but the current implementation requires some extra steps for example to calculate a time period:

```
start_time = cron.get_prev(datetime)
cron.get_next(datetime) # unnecessary call that requires some computing
period = cron.get_current(datetime) - start_time
```

By adding an extra argument to get_next(update_cur=False) / get_prev(update_cur=False), this additional call would no longer be necessary, resulting in cleaner code overall.

**Comment by kiorky** [comment]
would #83 addresses your problem ?

**Comment by kiorky** [comment]
would https://github.com/kiorky/croniter/issues/84 address your problem ?

**Comment by Fliens** [comment]
Yes absolutelty!

**Comment by kiorky** [comment]
https://pypi.org/project/croniter/3.0.1/ released
