### ISSUE TITLE
Why does get_next() return a real day for the incorrect cron expression? ('0 0 0 1 0') 

### ISSUE THREAD

**Issue by leemurus** [pallets-eco/croniter#9]
On wikipedia, day cannot be 0. https://en.wikipedia.org/wiki/Cron. Why do you allow?

**Comment by kiorky** [comment]
duplicate #6 , please upgade.

**Comment by kiorky** [comment]
(if you have still

**Comment by kiorky** [comment]
related to #6, seees there is another cornercase, i'm looking at it.

**Comment by kiorky** [comment]
it's not for days but to support seconds repeat where in this case, fields are then shifted up to 6 and the 4th field becomes the day one.

As this case is pretty straightforward, i added some rule to check in in the new released ``croniter==1.2.0``

Believe me, cron corner cases are infinite and using misformed crontabs expression will still always give you opportunity for bad ranges.
