### ISSUE TITLE
Black formatter?

### ISSUE THREAD

**Issue by evanpurkhiser** [pallets-eco/croniter#99]
Would you accept a PR that applies the [black](https://github.com/psf/black) formatter?

> [!NOTE]
> We're using this library in Sentry as part of our cron monitoring product. I am looking at tackling the DST bugs that exist. I would like to also spend some time cleaning up the library source code to make it easier to contribute to.

**Comment by kiorky** [comment]
Well, that a long interrogation i have which says not a simple no.

Problem is that is is an very old basecode initiated by a non python programmer (not me :))  starting with `py-2.3` and the introduce changes of reformatting is a bit overwhelming not to say frightening related to stability and errors...

**Comment by kiorky** [comment]
For DST handling, also, there is a bit of spaghetti that needs to be refactored to both:
- refactor tests that make shortcuts around dst but are wrong per se.
- remove DST handling hacks for a proper DST handling.

That 's why i didnt had the time yet to tackle this by myself.

See #1 and the related attemps, where the later is not that useful as the idea is just to refactor DST handling properly from scratch.

**Comment by kiorky** [comment]
> Well, that a long interrogation i have which says not a simple no.
> 
> Problem is that is is an very old basecode initiated by a non python programmer (not me :)) starting with `py-2.3` and the introduce changes of reformatting is a bit overwhelming not to say frightening related to stability and errors...

Maybe i was not clear, i would eagerly see a black formatted croniter basecode, but at the condition to be insured not to have any regression :-) .

**Comment by kiorky** [comment]
Maybe can we process by a `/couple of methods/50-100th code lines/` changes  by one PR to facilitate review.

**Comment by evanpurkhiser** [comment]
Awesome!

I can make a few individual PRs that apply the black formatter.

are you worried the test cases wouldn’t not catch any regressions that (would quite unlikely) be introduced by black if we formatted it all in one go?

**Comment by kiorky** [comment]
> Awesome!
> 
> I can make a few individual PRs that apply the black formatter.
> 
> are you worried the test cases wouldn’t not catch any regressions that (would quite unlikely) be introduced by black if we formatted it all in one go?

cron is all about user input, test coverage is already large for this purpose, but yes, bad thing can happen.

**Comment by evanpurkhiser** [comment]
I am thinking for the tests files I might just apply black all out, since these are code that run in CI and is not code that is used in production, we can safely say that as long as tests run, everything will be safe.

**Comment by evanpurkhiser** [comment]
I will also add a Github Action that will apply black and can do one of two things:

1. Fail the PR and require the author apply black to their PR
2. Auto-commit a black formatting fix to their PR.

The later might be more annoying if we don't make it easy to setup black for development.

**Comment by evanpurkhiser** [comment]
Let's close this. The codebase is now blacked :)

**Comment by kiorky** [comment]
i just also added isort in the loop.
